swifter/swifter.py

Created general Transformation class, which is flexible for any transformation that dask implements. For now, only Rolling objects have support, but as other requests come in it will be easy to implement with this Transformation class, so long as Dask supports it.

Rolling object support

---

README.md
setup.py
swifter/__init__.py
swifter/swifter.py
swifter/tqdm_dask_progressbar.py

Overriding default options with set_npartitions and set_dask_threshold commands for improved generalizability for different use cases.

Option overrides and code styling with black

---

swifter/swifter.py

Use _SwifterObject base class to inherit from for downstream classes. This improves DRY principles and cleans up the code a bit.

Base class

---

setup.py

Hi @jmcarpenter2,
Many many thanks for the great tool you've developed!
I faced an issue when I tried to use swifter on a datetime pandas Series, with such a call:
```
data_frame['DATE_YEAR'] = data_frame['DATE'].swifter.apply(lambda x: x.year)
```
It raised a series of error, and particularly this one:
```
ImportError: IntProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
```
Therefore, as I wasn't in a Jupyter Notebook, I updated `ipywidgets` with `pip install ipywidgets` and it solved the issue. The installed ipywidgets version is 7.4.2.
I just added the installation of `ipywidgets>=7.4.2` in the setup.py file. Here is the pull request. Could you make the necessary checks and tell me if I have something to do? …

Required ipywidgets update

---

.circleci/config.yml
Pipfile
Pipfile.lock
README.md
docs/changelog.md
setup.py
swifter/__init__.py
swifter/swifter.py
swifter/swifter_tests.py

* Adding unit test coverage for series, dataframe, and rolling swifter applies
* Minor fixes for rolling swifter applies

Unit test coverage and minor rolling bug fixes

---

swifter/swifter.py
swifter/swifter_tests.py

* Refactor str_processing logic to allow_dask_processing logic for more clarity
* Added unittest for text processing as a lookup function and ensure it runs faster than pandas

Refactor str_processing to allow_dask_processing + text unittest

---

README.md
docs/changelog.md
setup.py
swifter/__init__.py
swifter/swifter.py

* If a dictionary is an element in the dataframe, the vectorized form of the apply fails without exception handling because KeyError is currently not an exception we are handling
* Add KeyError to list of exceptions we are handling to resolve this situation

KeyError exception should be handled in the case of a nested dictionary inside of the dataframe

---

docs/changelog.md
docs/documentation.md
setup.py
swifter/__init__.py
swifter/swifter.py

This PR is a revision of [#63](https://github.com/jmcarpenter2/swifter/pull/63).  Thanks to @rlynch-ironnet for proposing this improvement.
The aim here is to allow for custom progress bar descriptions, without allowing the user to override other progress bar parameters that could break the code e.g. `total`.

Custom progress_bar description

---

swifter/swifter.py

An idea how to fix #66 . 
WARNING: It just suppresses warning.

Change import from tqdm.autonotebook to import tqdm.auto. Fix #66

---

docs/changelog.md
setup.py
swifter/__init__.py
swifter/swifter.py

Made several simplifications to the code per suggestions from @ianozsvald in [#73](https://github.com/jmcarpenter2/swifter/issues/73)
* Rename some variables to be more intuitive
* Replace assertions with _validate_apply method
* Reduce unnecessary lines of code used

Simplify code

---

docs/changelog.md
docs/documentation.md
setup.py
swifter/__init__.py
swifter/swifter.py
swifter/swifter_tests.py

Resolve #26 
* Add support for resample apply
* Improve support for rolling apply

Improve transformations; add Resampler

---

.circleci/config.yml
swifter/swifter_tests.py

* Add tests where we are missing coverage

Increase test coverage

---

swifter/swifter.py
swifter/swifter_tests.py
swifter/swifter_tests.py.orig

Add tests and short-circuit for empty dataframes and series

Swifter.apply fails on empty Dataframes / Series

---

docs/changelog.md
setup.py
swifter/__init__.py

* Update version + changelog for release

Release 0.303

---

setup.py
swifter/__init__.py

Release 0.304

---

Pipfile
Pipfile.lock
docs/changelog.md
setup.py
swifter/__init__.py

Per #122 let's see if we can remove the pickle5 dependency

Remove pickle5 dependency

---

README.md

May solve #85
Example:
```
import pandas as pd
import swifter
def example():
df = pd.DataFrame(
np.array([[0.02114-0.9019j], [0.9778-0.3080j], [0.0207-0.9871j]]),
index=pd.Index([0, 200, 400]),
columns=pd.MultiIndex.from_tuples([('a', '1')]),
dtype='complex128'
)
base = df.applymap(np.angle)  # returns dataframe
bad = df.swifter.progress_bar(enable=False).applymap(lambda x: np.angle(x))  # returns array
good = df.swifter.progress_bar(enable=False).applymap(lambda x: float(np.angle(x)))  # returns dataframe
```

Update README.md - Explicit Type Casting

---

docs/documentation.md
swifter/swifter.py

* Pandas added new kwargs `offset` and `origin` for df.resample()
* Allow usage of these new kwargs in swifter

Add new kwargs for pandas resample

---

Pipfile
Pipfile.lock
README.md
setup.py
swifter/__init__.py
swifter/swifter.py
swifter/swifter_tests.py

* Had to recreate #154  because cross-repo CI/CD not working
* Additionally prevented the change from breaking the axis=1 applies
* Additionally removed the logging filter

Make modin extras optional; remove logging filter

---

.circleci/config.yml
Makefile
docker/Dockerfile
docker/Dockerfile-dev
docker/docker-compose.yml
docker/requirements-dev.txt
docs/changelog.md
docs/documentation.md
requirements.txt
setup.py
swifter/__init__.py
swifter/base.py
swifter/parallel_accessor.py
swifter/swifter.py
swifter/swifter_tests.py
swifter/tqdm_dask_progressbar.py
tox.ini

* debug the installation issues in #167  and #168 
* The pipenv dev environment is SUPER slow to change requirements.. 
* modin has too many dependencies, creates installation issues
* moving everything to docker and makefile commands
* linted the repo
* removed modin dependency which was causing major dependency issues during install-time
* then we can incorporate #169

Resolve installation issues

---

Makefile
docs/changelog.md
setup.py
swifter/__init__.py

Release 1.1.2

---

docs/changelog.md
setup.py
swifter/__init__.py

v1.3.2: Extras require

---

.circleci/config.yml
docker/Dockerfile-dev
docker/requirements-dev.txt
swifter/swifter_tests.py

Some or all of #148 #175 #176 and #202 may be related to Windows.
We need Windows CI, so adding it in this PR

Add Windows CI
